---
- name: Configure WebServers on prod1
  hosts: prod1
  become: True
  tasks:
    - name: Install Nginx
      apt: name=nginx
    - name: Copy site index.html   C
      copy: src=~/repo1/index.html dest=/var/www/html
    - name: restart Nginx
      service: name=nginx state=restarted
